title:              Yuan Dong
email:              yuan.dong@duke.edu
description:        
author:             Yuan Dong
baseurl:            "/yuan-dong.site"
url:                "https://yuan-dong.site"

# Social Profiles
twitter_username:   
github_username:    yuan-d0ng
facebook_username:  
instagram_username:  
linkedin_username: ydong04
philpeople_username: yuan-dong-1

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
